config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  get "/sign_up", to: "users#new", as: "sign_up" # not included in vagabond file

  get "/sign_in", to: "sessions#new"

  post "/sessions", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  get "/users/:id", to: "users#show"

  get "/children", to: "children#index", as:"children"

  get "/children/new", to: "children#new", as: "new_child"

  get "/children/:id", to: "children#show"

  get "/children/:id/edit", to: "children#edit"

  get "/videos", to: "videos#index", as: "videos"

  get "/videos/new", to: "videos#new", as: "new_video"

  post "/videos", to: "videos#create"

  get "/videos/:id", to: "videos#show"

  get "/videos/:id/edit", to: "videos#edit"

  post "videos/:id/include", to: "videos#include", as: "include_video"

  post "videos/:id/hide", to: "videos#hide", as: "hide_video"

  resources :users, :children, :videos, :sessions

end

app/models/video.rb
class Video < ActiveRecord::Base
	validates :title, presence: true
	# validates :description, allow_blank: true
	# validates :url, presence: true
	validates :embed, presence: true
	validates :shared, :inclusion => {:in => [true, false]}
	belongs_to :user
	has_many :children, through: :users

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	def index
		@videos = Video.all.order(updated_at: :desc)
		@user = current_user
		@logged_in = logged_in?
		render :videos
	end

	def new
		@user = current_user
		@logged_in = logged_in?
		@video = Video.new
		render :new # render new video
	end

	def create
		video_params = params.require(:video).permit(:title, :description, :embed, :shared, :userid)
		@video = Video.create(video_params)
		# @child.user.videos << @video
		current_user.videos << @video
		current_user.save
		redirect_to "/users/#{current_user.id}"
	end

	def show
		@user = current_user
		@logged_in = logged_in?
		@videos = Video.all
		# @video = Video.find(params[:id])
		# @child = User.find(@video.user_id)
		# @show = @user.show? @video
		# @hide = @user.hide? @video
		# render :show
		redirect_to "/users/#{current_user.id}"
	end

	def edit
		@user = current_user
		@logged_in = logged_in?
		id = params[:id]
			@video = Video.find(id)
	end

	def update
		id = params[:id]
			video = Video.find(id)

			updated_attributes = params.require(:video).permit(:title, :description, :embed, :shared)
			video.update_attributes(updated_attributes)
			redirect_to video
	end

	def destroy
		id = params[:id]
		video = Video.find(id)
		# child = Child.find(video.child_id)
		video.destroy
		redirect_to "/users/#{current_user.id}"
	end


end

=begin   IF THIS IS USED, MOVE IT BACK ABOVE THE END ITEM
	def include
		id = params[:id]
		video = Video.find(id)
		owner = User.find(video.user_id)
		video.included current_child # not sure about this part
		owner.save
		redirect_to "/videos/#{id}"
	end

	def hide
		id = params[:id]
		video = Video.find(id)
		owner = User.find(video.user_id)
		video.hide current_child # not sure about this part
		owner.save
		redirect_to "/videos/#{id}"
	end
=end

	

app/helpers/videos_helper.rb
module VideosHelper

	def showVideo child
		child = Child.where("child_id = ? AND user_id = ?", child.id, user.id)
		# if include
		# not sure about what to include here
	end

	def hideVideo child
		child = Child.where("child_id = ? AND user_id = ?", child.id, user.id)
		# if hide
		# not sure about what to include here
	end

	def shareVideo user
		# need something here to allow users to share their videos with other users
	end





require 'google/api_client'
require 'google/api_client/client_secrets'
require 'json'
require 'launchy'
require 'thin'

RESPONSE_HTML = <<stop
<html>
  <head>
    <title>OAuth 2 Flow Complete</title>
  </head>
  <body>
    You have successfully completed the OAuth 2 flow. Please close this browser window and return to your program.
  </body>
</html>
stop

FILE_POSTFIX = '-oauth2.json'

# Small helper for the sample apps for performing OAuth 2.0 flows from the command
# line. Starts an embedded server to handle redirects.
class CommandLineOAuthHelper

  def initialize(scope)
    credentials = Google::APIClient::ClientSecrets.load
    @authorization = Signet::OAuth2::Client.new(
      :authorization_uri => credentials.authorization_uri,
      :token_credential_uri => credentials.token_credential_uri,
      :client_id => credentials.client_id,
      :client_secret => credentials.client_secret,
      :redirect_uri => credentials.redirect_uris.first,
      :scope => scope
    )
  end

  # Request authorization. Checks to see if a local file with credentials is present, and uses that.
  # Otherwise, opens a browser and waits for response, then saves the credentials locally.
  def authorize
    credentialsFile = $0 + FILE_POSTFIX

    if File.exist? credentialsFile
      File.open(credentialsFile, 'r') do |file|
        credentials = JSON.load(file)
        @authorization.access_token = credentials['access_token']
        @authorization.client_id = credentials['client_id']
        @authorization.client_secret = credentials['client_secret']
        @authorization.refresh_token = credentials['refresh_token']
        @authorization.expires_in = (Time.parse(credentials['token_expiry']) - Time.now).ceil
        if @authorization.expired?
          @authorization.fetch_access_token!
          save(credentialsFile)
        end
      end
    else
      auth = @authorization
      url = @authorization.authorization_uri().to_s
      server = Thin::Server.new('0.0.0.0', 8080) do
        run lambda { |env|
          # Exchange the auth code & quit
          req = Rack::Request.new(env)
          auth.code = req['code']
          auth.fetch_access_token!
          server.stop()
          [200, {'Content-Type' => 'text/html'}, RESPONSE_HTML]
        }
      end

      Launchy.open(url)
      server.start()

      save(credentialsFile)
    end

    return @authorization
  end

  def save(credentialsFile)
    File.open(credentialsFile, 'w', 0600) do |file|
      json = JSON.dump({
        :access_token => @authorization.access_token,
        :client_id => @authorization.client_id,
        :client_secret => @authorization.client_secret,
        :refresh_token => @authorization.refresh_token,
        :token_expiry => @authorization.expires_at
      })
      file.write(json)
    end
  end
end

end

app/views/videos/edit.html.erb
<%= render partial: "/layouts/navbar" %>

<br><br>
 <div class="col-md-3"></div>
<div class= "panel col-md-6 shadow-z-2">
<h1>Edit Video</h1>
<hr>
<%= form_for @video do |f| %>
	<br><div>
		<%= f.text_field :title, placeholder: "Book Title", size: "60x12", class: "form-control floating-label" %>
	</div><br>
	<div>
		<%= f.text_area :description, placeholder: "Description", size: "60x3", class: "form-control floating-label" %>
	</div><br>
	  <div>
    <%= f.text_field :embed, placeholder: "YouTube 'EMBED' code - all of it", size: "60x12", class: "form" %>  
  </div><br>
  <div class="green">
  	<%= f.check_box :shared, size: "2x2" %>
    <%= f.label "Share this book with other users" %>
  </div>

	<%= f.submit "Edit!!!", :class => "btn btn-material-green" %><br><br>
<% end %>
</div>
<div class="col-md-3"></div>

<container
<div class="col-md-12"></div><br>


    <button class="btn btn-raised btn-material-deep-orange" data-toggle="modal" data-target="#complete-dialog">Delete this Video </button><br>

    <div id="complete-dialog" class="modal fade" tabindex="-1">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title">Confirm</h4>
          </div>
          <div class="modal-body">

            <p class="black">Are sure you want to delete "<%= @video.title %>" ?</p>
            

          </div>
          <div class="modal-footer">
            <%= button_to "Delete", @video, method: :delete , class: "btn btn-raised btn-material-deep-orange"%>
          </div>
        </div>
      </div>
    </div>
</container>

app/views/videos/new.html.erb
<%= render partial: "/layouts/navbar" %>

<h1>New Book</h1>
<%= form_for @video do |f| %>
  <div>
    <%= f.text_field :title, placeholder: "Book Title", size: "60x12", class: "form" %>
  </div><br>
  <div>
    <%= f.text_area :description, placeholder: "Description of your book", size: "60x3", class: "form" %>
  </div><br><br>
  <div><h5 class="green citycard">1. From the YouTube page, click on the Share link below the video.<br><br>2. Below that, click on the Embed option and copy everything<br>from the box and paste it here in the box below.<br><br></h5><br></div><br>
  <div>
    <%= f.text_field :embed, placeholder: "YouTube 'EMBED' code - all of it", size: "60x12", class: "form" %>  
  </div><br>
  <div>
  	<%= f.check_box :shared, size: "2x2" %>
    <%= f.label "Share this book with other users" %>
  </div>
  <div>
    <%= f.hidden_field :user_id %>
  </div>
  <%= f.submit "Submit", :class => "btn btn-material-green" %>
<% end %> 

app/views/videos/show.html.erb
<%= render partial: "/layouts/navbar" %>

app/views/videos/videos.html.erb
<%= render partial: "/layouts/navbar" %>

<h1>All Books</h1>
<% @videos.reverse.each do |post| %>
<!-- <div class="col-md-3"></div> -->
<div class="card shadow-z-2">
<h4><%= video.title %></h4><hr>
<p><%= video.description %></p>
<!--   <% post_author = User.find(post.user_id)%>
  <% post_city = City.find(post.city_id)%>
  <hr>
 <h5> Post by <%=post_author.name%>, about <%=post_city.name%>, with a score of <%= post.get_likes.size - post.get_dislikes.size%>.</h5> -->
</div>



<!-- This is from the youtube gem -->
<div class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'YT APIv3', root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Videos', root_path %></li>
      <li><%= link_to 'Add Video', new_video_path %></li>
    </ul>
  </div>
</div>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<!-- End of youtube gem stuff -->