config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  get "/sign_up", to: "users#new", as: "sign_up" # not included in vagabond file

  get "/sign_in", to: "sessions#new"

  post "/sessions", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  get "/users/:id", to: "users#show"

  get "/children", to: "children#index", as:"children"

  get "/children/new", to: "children#new", as: "new_child"

  get "/children/:id", to: "children#show"

  get "/children/:id/edit", to: "children#edit"

  get "/videos", to: "videos#index", as: "videos"

  get "/videos/new", to: "videos#new", as: "new_video"

  post "/videos", to: "videos#create"

  get "/videos/:id", to: "videos#show"

  get "/videos/:id/edit", to: "videos#edit"

  post "videos/:id/include", to: "videos#include", as: "include_video"

  post "videos/:id/hide", to: "videos#hide", as: "hide_video"

  resources :users, :children, :videos, :sessions

end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-success">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-success-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button><% if @logged_in %>
        <a href="/users/<%= @user.id %>"><% else %><a href="/"><%end%><img src="" height="55"></a>
  </div>
  <div class="navbar-collapse collapse navbar-success-collapse">
    <ul class="nav navbar-nav">
      <% if @logged_in %>
        <li><a href="/users/<%= @user.id %>">My Page</a></li>
        <li class = "dropdown">
          <a href="bootstrap-elements.html" data-target="#" class-"dropdown-toggle" data-toggle="dropdown">Books <b class="caret"></b></a>
            <ul class = "dropdown-menu">
              <!-- <li><a href="/videos">All Books</a></li> -->
              <li><a class="black" href="/videos/new">Add a New Book</a></li>
              <!-- <li><a href="/videos/edit">Edit a Book</a></li> -->
            </ul>

        <li class = "dropdown">
          <a href="bootstrap-elements.html" data-target="#" class-"dropdown-toggle" data-toggle="dropdown">Children <b class="caret"></b></a>
            <ul class = "dropdown-menu">
              <% @children.each do |child| %>
                <div>
                  <li><a class="black" href = "/children/<%= child.id %>"><%= child.name %></a></li> 
                    <% end unless @children.nil? %>
                  <li><a class="black" href = "/children/new" >Add a New Child</a></li>
            </ul>
    <!--<li class="active"><a href="/videos">All Books</a></li> -->
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="/users/<%= @user.id %>/edit">Edit Profile</a></li>
  			<li><%= link_to "Log out", logout_path, method: :delete %></li>

		  <% else %>
			 <li><a href="/sign_in">Log in</a></li>
		  <% end %>
    
      </ul>
  </div>
</div>

app/views/layouts/_navbarLogin.html.erb
<div class="navbar navbar-success">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-success-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button><% if @logged_in %>
        <a href="/users/<%= @user.id %>"><% else %><a href="/"><%end%><img src="" height="55"></a>
  </div>
  <div class="navbar-collapse collapse navbar-success-collapse">
    <ul class="nav navbar-nav">
      <% if @logged_in %>
        <li><a href="/users/<%= @user.id %>">My Page</a></li>
        <li class = "dropdown">
          <a href="bootstrap-elements.html" data-target="#" class-"dropdown-toggle" data-toggle="dropdown">Books <b class="caret"></b></a>
            <ul class = "dropdown-menu">
              <!-- <li><a href="/videos">All Books</a></li> -->
              <li><a class="black" href="/videos/new">Add a New Book</a></li>
              <!-- <li><a href="/videos/edit">Edit a Book</a></li> -->
            </ul>

        <li class = "dropdown">
          <a href="bootstrap-elements.html" data-target="#" class-"dropdown-toggle" data-toggle="dropdown">Children <b class="caret"></b></a>
            <ul class = "dropdown-menu">
              <% @children.each do |child| %>
                <div>
                  <li><a class="black" href = "/children/<%= child.id %>"><%= child.name %></a></li> 
                    <% end unless @children.nil? %>
                  <li><a class="black" href = "/children/new" >Add a New Child</a></li>
            </ul>
    <!--<li class="active"><a href="/videos">All Books</a></li> -->
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="/users/<%= @user.id %>/edit">Edit Profile</a></li>
  			<li><%= link_to "Log out", logout_path, method: :delete %></li>

		  <% else %>
       <li><a href="/">Home</a></li>
			 <li><a href="/sign_up">Sign up</a></li>
		  <% end %>
    
      </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReadItAgain</title>
    <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<script src="//code.jquery.com/jquery.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

<script src="https://apis.google.com/js/platform.js" async defer></script>
<meta name="google-signin-client_id" content="innate-tempo-109222.apps.googleusercontent.com">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>